export enum Routes {
  //NAVIGATORS

  HOME = 'HOME',
  AUTH = 'AUTH',
  AUTH_NEW = 'AUTH_NEW',
  PROFILE = 'PROFILE',
  TABS = 'TABS',
  FILTER = 'FILTER',
  MODAL = 'MODAL',
  ORDER = 'ORDER',
  FAVORITE = 'FAVORITE',
  ROOM = 'ROOM',
  APPLICATON = 'APPLICATON',
  VIP = 'VIP',
  REPORT = 'REPORT',

  SPLASH = 'SPLASH',

  //AUTH
  SIGN_UP_END = 'SIGN_UP_END',
  SIGN_UP = 'SIGN_UP',
  SIGN_IN = 'SIGN_IN',
  SIGN_UP_MAIN = 'SIGN_UP_MAIN',
  CHANGE_ROLE = 'CHANGE_ROLE',
  CHANGE_LANG = 'CHANGE_LANG',
  CONFIRM_PHONE = 'CONFIRM_PHONE',
  CONFIRM_CODE = 'CONFIRM_CODE',

  //HOME
  HOME_LIST = 'HOME_LIST',
  EXECUTOR_LIST = 'EXECUTOR_LIST',
  CATEGORY_CHILDREN_LIST = 'CATEGORY_CHILDREN_LIST',
  EXECUTOR_DETAIL = 'EXECUTOR_DETAIL',
  ORDER_DETAIL = 'ORDER_DETAIL',
  ORDER_USER = 'ORDER_USER',
  APPLICATION_CREATE = 'APPLICATION_CREATE',
  REVIEW_CREATE = 'REVIEW_CREATE',

  //PROFILE
  PROFILE_LIST = 'PROFILE_LIST',
  PROFILE_EDIT = 'PROFILE_EDIT',
  PROFILE_SETTINGS = 'PROFILE_SETTINGS',
  VERIFICATION = 'VERIFICATION',
  MY_CARD = 'MY_CARD',
  ORDER_NAVIGATOR = 'ORDER_NAVIGATOR',
  RESPONSE_LIST = 'RESPONSE_LIST',
  CREATE_EXECUTOR = 'CREATE_EXECUTOR',
  REFERRAL_PROGRAM = 'REFERRAL PROGRAM',
  PROFILE_SETTINGS_DETAILS_PAGE = 'PROFILE_SETTINGS_DETAILS_PAGE',

  //FILTER
  FILTER_LIST = 'FILTER_LIST',
  SPECIALIZATION_LIST = 'SPECIALIZATION_LIST',

  //ORDER
  ORDER_CREATE = 'ORDER_CREATE',
  ORDER_UPDATE = 'ORDER_UPDATE',
  PROFILE_ORDER_LIST = 'PROFILE_ORDER_LIST',
  PROFILE_ORDER_DETAIL = 'PROFILE_ORDER_DETAIL',

  //APPLICATION
  APPLICATION_LIST = 'APPLICATION_LIST',

  //VIP
  VIP_LIST = 'VIP_LIST',

  //ROOM
  ROOM_LIST = 'ROOM_LIST',
  ROOM_DETAIL = 'ROOM_DETAIL',

  //FAVORITE
  FAVORITE_LIST = 'FAVORITE_LIST',

  //REPORT
  REPORT_LIST = 'REPORT_LIST',
  REPORT_CREATE = 'REPORT_CREATE',
}
